# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}

      - name: Use Node.js '14.x'
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install yarn
        run: npm install -g yarn

      - name: Install client dependencies
        working-directory: client
        run: yarn install

      - name: Install deploy dependencies
        working-directory: deploy
        run: yarn install

      - name: Deploy resume
        working-directory: deploy
        run: yarn run deploy repo_url=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY branch=$GITHUB_REF

      - name: Commit
        run: |
          git config --global user.name $GITHUB_ACTOR
          git add -A
          git commit -m "Deploy resume"

      - name: Push
        run: |
          git push
