# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}

      - name: Use Node.js '14.x'
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install Resume Dependencies
        working-directory: resume
        run: npm install

      - name: Build Client
        working-directory: resume
        run: npm run build

      - name: Install Utils Dependencies
        working-directory: utils
        run: npm install

      - name: Release Resume
        working-directory: utils
        run: npm run release-resume

      - name: Push
        run: |
          git config --global user.name 'lumyjuwon'
          git config --global user.email 'lumyjuwon@gmail.com'
          git add -A
          git commit -m "Release Resume"
          git push
